### ISSUE TITLE
slow loading

### ISSUE THREAD

**Issue by yohai2016** [pebble-dev/android-store-app#2]
if i leave the app with the home button and re enter in the app , the app open very quickly but if use the back button the app reload slowly

**Comment by WuerfelDev** [comment]
Same when changing the phones orientation while the app is opened, so it is something in the onCreate methods or so

**Comment by KonradIT** [comment]
Can reproduce, in my case the loading times are nearly null

**Comment by yohai2016** [comment]
yes every time
